### ISSUE TITLE
Add support for screensaver inhibition

### ISSUE THREAD

**Issue by KawaiiDinosaur** [flathub/org.duckstation.DuckStation#10]
While playing with a gamepad, the emulator doesn't inhibit the screensaver from showing up. I believe that adding dbus interface "org.freedesktop.ScreenSaver" should fix it, at least on KDE.

**Comment by j8r** [comment]
I doubt it'll work, since the `xdg-screensaver` command is used: https://github.com/stenzek/duckstation/blob/master/src/frontend-common/inhibit_screensaver.cpp.

Modifications have to be done upstream first.
