### ISSUE TITLE
BigPicture - qt Gui appears after quitting Game

### ISSUE THREAD

**Issue by link99x** [flathub/org.duckstation.DuckStation#12]
After quitting a Game in BigPicture Mode, the qt Gui appears. The BigPicture Mode is still running in the background.
The behavior is gone, after closing the qt window, til a fresh restart of the app.

**Comment by j8r** [comment]
I doubt it is related to the Flatpak packaging.
To be sure you could compile DuckStation and see if it still happens. If it does unfortunately, unless one can open a PR directly to fix it, the bug will stay as the maintainer doesn't accept issues anymore.
As a workaround you can also start DuckStation with `-nogui`.

**Comment by link99x** [comment]
Thanks for your fast reply. The hint with the -nogui argument was really good. Didn't know this parameter.
Works fine now, not perfect, but for that purpose great. You are problay right, the "issue" is related to the main package. So, my hope was, that this github channel has a connection with the main package.
Thanks for the great support, you helped me a lot!
