### ISSUE TITLE
BigPicture - per game Save State Issue

### ISSUE THREAD

**Issue by link99x** [flathub/org.duckstation.DuckStation#13]
When choosing to save a "per game save state" in the menu (BigPicture Mode), a "global save state" will be created.
Workaround: Define a Hotkey for this function.

**Comment by j8r** [comment]
I'm afraid we can't do much, it is rated to emulator software, not the Flatpak package itself.
However, the DuckStation maintainer doesn't accept issues anymore.

**Comment by j8r** [comment]
I'm afraid we can't do much, it is related to the emulator software, not the Flatpak package itself.
However, the DuckStation maintainer doesn't accept issues anymore.
