### ISSUE TITLE
Re-enable the nogui build

### ISSUE THREAD

**Issue by HybridEidolon** [flathub/org.duckstation.DuckStation#21]
Recently the nogui build was disabled by default in the CMake script. This build has a slightly better user experience on media centers and handhelds like the Steam Deck compared to using the Qt GUI with Big Picture UI. The compositor for SteamOS in particular has some issues ensuring that the Big Picture window remains on top when switching between games.

**Comment by j8r** [comment]
The legacy nogui interface is no longer maintained since https://github.com/stenzek/duckstation/commit/68866f3174228194cd86c9caef1038e1721c96dc, thus broken.
 The best would be to enhance the new Qt one, which is supposed to be similar.

**Comment by j8r** [comment]
Closing the issue, the old nogui is no longer maintained and should not be restored. The current interface should do mostly what it did.
