### ISSUE TITLE
Can not add read and write breakpoints

### ISSUE THREAD

**Issue by buruto** [flathub/org.duckstation.DuckStation#33]
In DuckStation I can add execute breakpoints but not read and write breakpoints.

I want to be able to add read and write breakpoints and not only execute breakpoints.

This can be very useful for both cheaters and hackers who want to make their own cheats that can not be found on the internet.

Note that both read and write breakpoints don't have to work while dynamic recompilation is used but at least while the emulated game is interpreted.

When the interpreter encounters any `sb`, `sh` or `sw` instruction then the interpreter pauses the emulator if and only if there is an active write breakpoint in the memory address before the `sb`, `sh` or `sw` instruction is going to write to.

And when the interpreter encounters any `lb`, `lbu`, `lh`, `lhu` or `lw` instruction then the interpreter pauses the emulator if and only if there is an active read breakpoint in the memory address that the `lb`, `lbu`, `lh`, `lhu` or `lw` instruction is going to read from.

Any active execute breakpoint pauses the emulator when the PC register reaches it.

If the emulated game is interpreted then the interpreter pauses the emulator when the interpreter encounters any instruction that an execute breakpoint was placed on and the execute breakpoint is active of course.

No need to worry about game both speed and performance at all because in today gaming computers, processors and hardware PS1 and PSX games can be interpreted pretty quickly.

I don't think at all that this feature should be hard at all to program the interpreter to behave like this to support both read and write breakpoints but please let me know if I am wrong.

**Comment by buruto** [comment]
I have solved it by myself.

**Comment by wafflewizard1** [comment]
thank you for the help

**Comment by wafflewizard1** [comment]
can you tell me how you did it?
