### ISSUE TITLE
Xbox One S controller being detected everywhere on the system, except DuckStation flatpak

### ISSUE THREAD

**Issue by ivanaugustobd** [flathub/org.duckstation.DuckStation#6]
As someone of those who prefer Flatpak over AppImage, first of all thanks for this port.

I'm using Fedora 34/Flatpak 1.10/Nvidia GTX1050 with driver v.470/X11/Gnome 40 and have installed [xpadneo](https://atar-axis.github.io/xpadneo/), and after checked with both `io.gitlab.sdl_jstest.sdl_jstest` and `io.gitlab.sdl_jstest2.sdl_jstest`, my controller seems to be working just fine, both via usb and even via Bluetooth.

Although in DuckStation it simply does nothing when I use the auto mapping or even the manual key-by-key binding. I've already researched  A LOT about it, even coming to the devices=all trick on the json build, but as I've seen here you have already enabled it.

Someone has any ideas about what could be happening? Even my browser can [detect the controller](https://gamepad-tester.com/) but only DuckStation no :/

**Comment by ivanaugustobd** [comment]
Just tested with PCSX2 Flatpak version, and it works fine there too

**Comment by j8r** [comment]
Thanks @ivanaugustobd! Does it work on the upstream DuckStation AppImage? If not, nothing to do here.

**Comment by ivanaugustobd** [comment]
What, it didn't work there too. Guess I'll "move" this issue to their official repo.
Thanks!

**Comment by ivanaugustobd** [comment]
While opening the issue I've tried a last time by removing the old config folder (shared with my Windows installation) and now it works, lol
