### ISSUE TITLE
Upgrade runtime to 6.4?

### ISSUE THREAD

**Issue by ludvigng** [flathub/org.duckstation.DuckStation#64]
Hello!

Would it be possible to upgrade to the newer 6.4 runtime for this? 6.3 hasn't seen much changes since july last year.

Kind regards,

**Comment by j8r** [comment]
I tried to upgrade it in https://github.com/flathub/org.duckstation.DuckStation/pull/47, no luck even after trying to add the faulting libraries.

**Comment by ludvigng** [comment]
Oh, my bad. I checked both open and closed issues, didn't think about checking pull requests.

I tried building #47 on my machine, and it failed with
```
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.1.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/libpng16.so.16: undefined reference to `inflateReset2@ZLIB_1.2.3.4'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.1.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9'
```
which I suspect is the same error you received. After digging a bit, I noticed that duckstation seems to bundle its own zlib: https://github.com/stenzek/duckstation/tree/master/dep/zlib

I wonder if it's simply because runtime 6.3 comes with the same version of zlib as the one bundled with duckstation, 1.2.11? Runtime 6.4 seems to come with zlib 1.2.12 instead.

**Comment by j8r** [comment]
Yes, that's the error I got too. We don't have any issue on PCSX2 however.
If anyone finds a solution, it is welcomed.

**Comment by ludvigng** [comment]
They also seem to bundle libpng while I suspect that duckstation uses the system version which would be compiled against zlib 1.2.12 maybe? I'm far from an expert on this though, but I'll see if I can try messing around with it sometime soon.

**Comment by j8r** [comment]
I've found a workaround - using an updated zlib 1.2.12.
