### ISSUE TITLE
The app doesn't save the game into the Software memory card

### ISSUE THREAD

**Issue by Master811129** [flathub/org.duckstation.DuckStation#9]
it can save the state but it can't save to the memory card.
I have the AppImage of this software and that does not have this issue so it's probably a sandboxing issue

**Comment by j8r** [comment]
Have you error log to share?

**Comment by j8r** [comment]
Have you any error log to share?

**Comment by Calinou** [comment]
I can't reproduce this on Fedora 34 and the latest version of this Flatpak as of writing (2a4a12d62f13052dff0fd9cff25fa4b164e407f5).

**Comment by Master811129** [comment]
Fixed in Latest release for me probably the AppImage was older/newer and i encounter a bug or something. Sorry for taking your time.
